M48
; DRILL file {KiCad 9.0.0} date 2026-01-11T16:58:44-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-11T16:58:44-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X129.787Y-101.405
X135.567Y-101.405
T2
X142.189Y-68.25
X142.189Y-71.25
T3
X142.49Y-45.75
X142.74Y-110.577
X159.6Y-45.93
M30
