#ifndef GENERATED_ASN1SCC_HorusBinaryV3_H
#define GENERATED_ASN1SCC_HorusBinaryV3_H
/*
Code automatically generated by asn1scc tool
*/
#include "assert_override.h"
#include "asn1crt.h"
#include "asn1crt_encoding.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- BitFlags --------------------------------------------*/
typedef struct {
    flag b0;
    flag b1;
    flag b2;
    flag b3;
    flag b4;
    flag b5;
    flag b6;
    flag b7;

} BitFlags;

#define ERR_BITFLAGS		41  /**/
#define ERR_BITFLAGS_B0		1  /**/
#define ERR_BITFLAGS_B1		6  /**/
#define ERR_BITFLAGS_B2		11  /**/
#define ERR_BITFLAGS_B3		16  /**/
#define ERR_BITFLAGS_B4		21  /**/
#define ERR_BITFLAGS_B5		26  /**/
#define ERR_BITFLAGS_B6		31  /**/
#define ERR_BITFLAGS_B7		36  /**/
flag BitFlags_IsConstraintValid(const BitFlags* pVal, int* pErrCode);

void BitFlags_Initialize(BitFlags* pVal);

#define ERR_UPER_ENCODE_BITFLAGS		42  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B0		2  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B1		7  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B2		12  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B3		17  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B4		22  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B5		27  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B6		32  /**/
#define ERR_UPER_ENCODE_BITFLAGS_B7		37  /**/
#define BitFlags_REQUIRED_BYTES_FOR_ENCODING       1
#define BitFlags_REQUIRED_BITS_FOR_ENCODING        8

flag BitFlags_Encode(const BitFlags* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_BITFLAGS		43  /**/
#define ERR_UPER_DECODE_BITFLAGS_B0		3  /**/
#define ERR_UPER_DECODE_BITFLAGS_B1		8  /**/
#define ERR_UPER_DECODE_BITFLAGS_B2		13  /**/
#define ERR_UPER_DECODE_BITFLAGS_B3		18  /**/
#define ERR_UPER_DECODE_BITFLAGS_B4		23  /**/
#define ERR_UPER_DECODE_BITFLAGS_B5		28  /**/
#define ERR_UPER_DECODE_BITFLAGS_B6		33  /**/
#define ERR_UPER_DECODE_BITFLAGS_B7		38  /**/
flag BitFlags_Decode(BitFlags* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- CustomFieldValues --------------------------------------------*/
typedef char CustomFieldValues_horusStr[256];


typedef struct {
    int nCount;
    asn1SccSint arr[4];
} CustomFieldValues_horusInt;


typedef struct {
    int nCount;
    asn1Real arr[4];
} CustomFieldValues_horusReal;

typedef enum {
    CustomFieldValues_NONE,
    horusStr_PRESENT,
    horusInt_PRESENT,
    horusReal_PRESENT,
    horusBool_PRESENT
} CustomFieldValues_selection;

typedef union {
    CustomFieldValues_horusStr horusStr;
    CustomFieldValues_horusInt horusInt;
    CustomFieldValues_horusReal horusReal;
    BitFlags horusBool;
} CustomFieldValues_unchecked_union;

typedef struct {
    CustomFieldValues_selection kind;

    CustomFieldValues_unchecked_union u;
} CustomFieldValues;

#define ERR_CUSTOMFIELDVALUES_HORUSSTR		46  /*(FROM("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_ +/=-.")^SIZE (0..255))*/
flag CustomFieldValues_horusStr_IsConstraintValid(const CustomFieldValues_horusStr pVal, int* pErrCode);

#define ERR_CUSTOMFIELDVALUES_HORUSINT		56  /*(SIZE(1..4))*/
#define ERR_CUSTOMFIELDVALUES_HORUSINT_ELM		51  /**/
flag CustomFieldValues_horusInt_IsConstraintValid(const CustomFieldValues_horusInt* pVal, int* pErrCode);

#define ERR_CUSTOMFIELDVALUES_HORUSREAL		66  /*(SIZE(1..4))*/
#define ERR_CUSTOMFIELDVALUES_HORUSREAL_ELM		61  /**/
flag CustomFieldValues_horusReal_IsConstraintValid(const CustomFieldValues_horusReal* pVal, int* pErrCode);

#define ERR_CUSTOMFIELDVALUES		76  /**/
#define ERR_CUSTOMFIELDVALUES_HORUSBOOL		71  /**/
flag CustomFieldValues_IsConstraintValid(const CustomFieldValues* pVal, int* pErrCode);

void CustomFieldValues_horusStr_Initialize(CustomFieldValues_horusStr pVal);
void CustomFieldValues_horusInt_Initialize(CustomFieldValues_horusInt* pVal);
void CustomFieldValues_horusReal_Initialize(CustomFieldValues_horusReal* pVal);
void CustomFieldValues_Initialize(CustomFieldValues* pVal);

#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES		77  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSSTR		47  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSINT		57  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSINT_ELM		52  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSREAL		67  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSREAL_ELM		62  /**/
#define ERR_UPER_ENCODE_CUSTOMFIELDVALUES_HORUSBOOL		72  /**/
#define CustomFieldValues_REQUIRED_BYTES_FOR_ENCODING       225
#define CustomFieldValues_REQUIRED_BITS_FOR_ENCODING        1795

flag CustomFieldValues_Encode(const CustomFieldValues* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CUSTOMFIELDVALUES		78  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSSTR		48  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSINT		58  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSINT_ELM		53  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSREAL		68  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSREAL_ELM		63  /**/
#define ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSBOOL		73  /**/
flag CustomFieldValues_Decode(CustomFieldValues* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- AdditionalSensorType --------------------------------------------*/
typedef char AdditionalSensorType_name[21];
typedef struct {
    unsigned long name:1;
    unsigned long values:1;
} AdditionalSensorType_exist;
typedef struct {
    AdditionalSensorType_name name;
    CustomFieldValues values;

    AdditionalSensorType_exist exist;

} AdditionalSensorType;

#define ERR_ADDITIONALSENSORTYPE_NAME		81  /*(FROM("abcdefghijklmnopqrstuvwxyz0123456789-")^SIZE (1..20))*/
flag AdditionalSensorType_name_IsConstraintValid(const AdditionalSensorType_name pVal, int* pErrCode);

#define ERR_ADDITIONALSENSORTYPE		91  /**/
#define ERR_ADDITIONALSENSORTYPE_VALUES		86  /**/
flag AdditionalSensorType_IsConstraintValid(const AdditionalSensorType* pVal, int* pErrCode);

void AdditionalSensorType_name_Initialize(AdditionalSensorType_name pVal);
void AdditionalSensorType_Initialize(AdditionalSensorType* pVal);

#define ERR_UPER_ENCODE_ADDITIONALSENSORTYPE		92  /**/
#define ERR_UPER_ENCODE_ADDITIONALSENSORTYPE_NAME		82  /**/
#define ERR_UPER_ENCODE_ADDITIONALSENSORTYPE_VALUES		87  /**/
#define AdditionalSensorType_REQUIRED_BYTES_FOR_ENCODING       241
#define AdditionalSensorType_REQUIRED_BITS_FOR_ENCODING        1922

flag AdditionalSensorType_Encode(const AdditionalSensorType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_ADDITIONALSENSORTYPE		93  /**/
#define ERR_UPER_DECODE_ADDITIONALSENSORTYPE_NAME		83  /**/
#define ERR_UPER_DECODE_ADDITIONALSENSORTYPE_VALUES		88  /**/
flag AdditionalSensorType_Decode(AdditionalSensorType* pVal, BitStream* pBitStrm, int* pErrCode);


typedef struct {
    int nCount;
    AdditionalSensorType arr[4];
} AdditionalSensors;

#define ERR_ADDITIONALSENSORS		101  /*(SIZE(1..4))*/
#define ERR_ADDITIONALSENSORS_ELM		96  /**/
flag AdditionalSensors_IsConstraintValid(const AdditionalSensors* pVal, int* pErrCode);

void AdditionalSensors_Initialize(AdditionalSensors* pVal);

#define ERR_UPER_ENCODE_ADDITIONALSENSORS		102  /**/
#define ERR_UPER_ENCODE_ADDITIONALSENSORS_ELM		97  /**/
#define AdditionalSensors_REQUIRED_BYTES_FOR_ENCODING       962
#define AdditionalSensors_REQUIRED_BITS_FOR_ENCODING        7690

flag AdditionalSensors_Encode(const AdditionalSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_ADDITIONALSENSORS		103  /**/
#define ERR_UPER_DECODE_ADDITIONALSENSORS_ELM		98  /**/
flag AdditionalSensors_Decode(AdditionalSensors* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- TemperatureSensors --------------------------------------------*/
typedef asn1SccSint TemperatureSensors_internal;

typedef asn1SccSint TemperatureSensors_external;

typedef asn1SccSint TemperatureSensors_custom1;

typedef asn1SccSint TemperatureSensors_custom2;

typedef struct {
    unsigned long internal:1;
    unsigned long external:1;
    unsigned long custom1:1;
    unsigned long custom2:1;
} TemperatureSensors_exist;
typedef struct {
    TemperatureSensors_internal internal;
    TemperatureSensors_external external;
    TemperatureSensors_custom1 custom1;
    TemperatureSensors_custom2 custom2;

    TemperatureSensors_exist exist;

} TemperatureSensors;

#define ERR_TEMPERATURESENSORS_INTERNAL		106  /*(-1023..1023)*/
flag TemperatureSensors_internal_IsConstraintValid(const TemperatureSensors_internal* pVal, int* pErrCode);

#define ERR_TEMPERATURESENSORS_EXTERNAL		111  /*(-1023..1023)*/
flag TemperatureSensors_external_IsConstraintValid(const TemperatureSensors_external* pVal, int* pErrCode);

#define ERR_TEMPERATURESENSORS_CUSTOM1		116  /*(-1023..1023)*/
flag TemperatureSensors_custom1_IsConstraintValid(const TemperatureSensors_custom1* pVal, int* pErrCode);

#define ERR_TEMPERATURESENSORS_CUSTOM2		121  /*(-1023..1023)*/
flag TemperatureSensors_custom2_IsConstraintValid(const TemperatureSensors_custom2* pVal, int* pErrCode);

#define ERR_TEMPERATURESENSORS		126  /**/
flag TemperatureSensors_IsConstraintValid(const TemperatureSensors* pVal, int* pErrCode);

void TemperatureSensors_internal_Initialize(TemperatureSensors_internal* pVal);
void TemperatureSensors_external_Initialize(TemperatureSensors_external* pVal);
void TemperatureSensors_custom1_Initialize(TemperatureSensors_custom1* pVal);
void TemperatureSensors_custom2_Initialize(TemperatureSensors_custom2* pVal);
void TemperatureSensors_Initialize(TemperatureSensors* pVal);

#define ERR_UPER_ENCODE_TEMPERATURESENSORS		127  /**/
#define ERR_UPER_ENCODE_TEMPERATURESENSORS_INTERNAL		107  /**/
#define ERR_UPER_ENCODE_TEMPERATURESENSORS_EXTERNAL		112  /**/
#define ERR_UPER_ENCODE_TEMPERATURESENSORS_CUSTOM1		117  /**/
#define ERR_UPER_ENCODE_TEMPERATURESENSORS_CUSTOM2		122  /**/
#define TemperatureSensors_REQUIRED_BYTES_FOR_ENCODING       6
#define TemperatureSensors_REQUIRED_BITS_FOR_ENCODING        48

flag TemperatureSensors_Encode(const TemperatureSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_TEMPERATURESENSORS		128  /**/
#define ERR_UPER_DECODE_TEMPERATURESENSORS_INTERNAL		108  /**/
#define ERR_UPER_DECODE_TEMPERATURESENSORS_EXTERNAL		113  /**/
#define ERR_UPER_DECODE_TEMPERATURESENSORS_CUSTOM1		118  /**/
#define ERR_UPER_DECODE_TEMPERATURESENSORS_CUSTOM2		123  /**/
flag TemperatureSensors_Decode(TemperatureSensors* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- MilliVoltSensors --------------------------------------------*/
typedef asn1SccUint MilliVoltSensors_battery;

typedef asn1SccUint MilliVoltSensors_solar;

typedef asn1SccUint MilliVoltSensors_custom1;

typedef asn1SccUint MilliVoltSensors_custom2;

typedef struct {
    unsigned long battery:1;
    unsigned long solar:1;
    unsigned long custom1:1;
    unsigned long custom2:1;
} MilliVoltSensors_exist;
typedef struct {
    MilliVoltSensors_battery battery;
    MilliVoltSensors_solar solar;
    MilliVoltSensors_custom1 custom1;
    MilliVoltSensors_custom2 custom2;

    MilliVoltSensors_exist exist;

} MilliVoltSensors;

#define ERR_MILLIVOLTSENSORS_BATTERY		131  /*(0..16383)*/
flag MilliVoltSensors_battery_IsConstraintValid(const MilliVoltSensors_battery* pVal, int* pErrCode);

#define ERR_MILLIVOLTSENSORS_SOLAR		136  /*(0..16383)*/
flag MilliVoltSensors_solar_IsConstraintValid(const MilliVoltSensors_solar* pVal, int* pErrCode);

#define ERR_MILLIVOLTSENSORS_CUSTOM1		141  /*(0..16383)*/
flag MilliVoltSensors_custom1_IsConstraintValid(const MilliVoltSensors_custom1* pVal, int* pErrCode);

#define ERR_MILLIVOLTSENSORS_CUSTOM2		146  /*(0..16383)*/
flag MilliVoltSensors_custom2_IsConstraintValid(const MilliVoltSensors_custom2* pVal, int* pErrCode);

#define ERR_MILLIVOLTSENSORS		151  /**/
flag MilliVoltSensors_IsConstraintValid(const MilliVoltSensors* pVal, int* pErrCode);

void MilliVoltSensors_battery_Initialize(MilliVoltSensors_battery* pVal);
void MilliVoltSensors_solar_Initialize(MilliVoltSensors_solar* pVal);
void MilliVoltSensors_custom1_Initialize(MilliVoltSensors_custom1* pVal);
void MilliVoltSensors_custom2_Initialize(MilliVoltSensors_custom2* pVal);
void MilliVoltSensors_Initialize(MilliVoltSensors* pVal);

#define ERR_UPER_ENCODE_MILLIVOLTSENSORS		152  /**/
#define ERR_UPER_ENCODE_MILLIVOLTSENSORS_BATTERY		132  /**/
#define ERR_UPER_ENCODE_MILLIVOLTSENSORS_SOLAR		137  /**/
#define ERR_UPER_ENCODE_MILLIVOLTSENSORS_CUSTOM1		142  /**/
#define ERR_UPER_ENCODE_MILLIVOLTSENSORS_CUSTOM2		147  /**/
#define MilliVoltSensors_REQUIRED_BYTES_FOR_ENCODING       8
#define MilliVoltSensors_REQUIRED_BITS_FOR_ENCODING        60

flag MilliVoltSensors_Encode(const MilliVoltSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_MILLIVOLTSENSORS		153  /**/
#define ERR_UPER_DECODE_MILLIVOLTSENSORS_BATTERY		133  /**/
#define ERR_UPER_DECODE_MILLIVOLTSENSORS_SOLAR		138  /**/
#define ERR_UPER_DECODE_MILLIVOLTSENSORS_CUSTOM1		143  /**/
#define ERR_UPER_DECODE_MILLIVOLTSENSORS_CUSTOM2		148  /**/
flag MilliVoltSensors_Decode(MilliVoltSensors* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    psmNotActive = 0,
    enabled = 1,
    acquisition = 2,
    tracking = 3,
    optimised = 4,
    inactive = 5
} GnssPowerSaveState;

// please use the following macros to avoid breaking code.
#define GnssPowerSaveState_psmNotActive psmNotActive
#define GnssPowerSaveState_enabled enabled
#define GnssPowerSaveState_acquisition acquisition
#define GnssPowerSaveState_tracking tracking
#define GnssPowerSaveState_optimised optimised
#define GnssPowerSaveState_inactive inactive

#define ERR_GNSSPOWERSAVESTATE		156  /*psmNotActive | enabled | acquisition | tracking | optimised | inactive*/
flag GnssPowerSaveState_IsConstraintValid(const GnssPowerSaveState* pVal, int* pErrCode);

void GnssPowerSaveState_Initialize(GnssPowerSaveState* pVal);

#define ERR_UPER_ENCODE_GNSSPOWERSAVESTATE		157  /**/
#define GnssPowerSaveState_REQUIRED_BYTES_FOR_ENCODING       1
#define GnssPowerSaveState_REQUIRED_BITS_FOR_ENCODING        3

flag GnssPowerSaveState_Encode(const GnssPowerSaveState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GNSSPOWERSAVESTATE		158  /**/
flag GnssPowerSaveState_Decode(GnssPowerSaveState* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- Telemetry --------------------------------------------*/
typedef char Telemetry_payloadCallsign[16];
typedef asn1SccUint Telemetry_sequenceNumber;

typedef asn1SccSint Telemetry_timeOfDaySeconds;

typedef asn1SccSint Telemetry_latitude;

typedef asn1SccSint Telemetry_longitude;

typedef asn1SccSint Telemetry_altitudeMeters;

typedef asn1SccUint Telemetry_velocityHorizontalKilometersPerHour;

typedef asn1SccUint Telemetry_gnssSatellitesVisible;

typedef asn1SccSint Telemetry_ascentRateCentimetersPerSecond;

typedef asn1SccUint Telemetry_pressurehPa_x10;

typedef asn1SccUint Telemetry_humidityPercentage;



typedef struct {
    int nCount;
    asn1SccSint arr[8];
} Telemetry_counts;
typedef struct {
    int nCount;
    byte arr[255];
} Telemetry_customData;

typedef struct {
    unsigned long extensionMarkerForASN1CC:1;
    unsigned long extraSensors:1;
    unsigned long velocityHorizontalKilometersPerHour:1;
    unsigned long gnssSatellitesVisible:1;
    unsigned long ascentRateCentimetersPerSecond:1;
    unsigned long pressurehPa_x10:1;
    unsigned long temperatureCelsius_x10:1;
    unsigned long humidityPercentage:1;
    unsigned long milliVolts:1;
    unsigned long counts:1;
    unsigned long gnssPowerSaveState:1;
    unsigned long customData:1;
} Telemetry_exist;
typedef struct {
    flag extensionMarkerForASN1CC;
    Telemetry_payloadCallsign payloadCallsign;
    Telemetry_sequenceNumber sequenceNumber;
    Telemetry_timeOfDaySeconds timeOfDaySeconds;
    Telemetry_latitude latitude;
    Telemetry_longitude longitude;
    Telemetry_altitudeMeters altitudeMeters;
    AdditionalSensors extraSensors;
    Telemetry_velocityHorizontalKilometersPerHour velocityHorizontalKilometersPerHour;
    Telemetry_gnssSatellitesVisible gnssSatellitesVisible;
    Telemetry_ascentRateCentimetersPerSecond ascentRateCentimetersPerSecond;
    Telemetry_pressurehPa_x10 pressurehPa_x10;
    TemperatureSensors temperatureCelsius_x10;
    Telemetry_humidityPercentage humidityPercentage;
    MilliVoltSensors milliVolts;
    Telemetry_counts counts;
    GnssPowerSaveState gnssPowerSaveState;
    Telemetry_customData customData;

    Telemetry_exist exist;

} Telemetry;

#define ERR_TELEMETRY_PAYLOADCALLSIGN		166  /*(FROM("-/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")^SIZE (1..15))*/
flag Telemetry_payloadCallsign_IsConstraintValid(const Telemetry_payloadCallsign pVal, int* pErrCode);

#define ERR_TELEMETRY_SEQUENCENUMBER		171  /*(0..65535)*/
flag Telemetry_sequenceNumber_IsConstraintValid(const Telemetry_sequenceNumber* pVal, int* pErrCode);

#define ERR_TELEMETRY_TIMEOFDAYSECONDS		176  /*(-1..86400)*/
flag Telemetry_timeOfDaySeconds_IsConstraintValid(const Telemetry_timeOfDaySeconds* pVal, int* pErrCode);

#define ERR_TELEMETRY_LATITUDE		181  /*(-9000000..9000000)*/
flag Telemetry_latitude_IsConstraintValid(const Telemetry_latitude* pVal, int* pErrCode);

#define ERR_TELEMETRY_LONGITUDE		186  /*(-18000000..18000000)*/
flag Telemetry_longitude_IsConstraintValid(const Telemetry_longitude* pVal, int* pErrCode);

#define ERR_TELEMETRY_ALTITUDEMETERS		191  /*(-1000..50000)*/
flag Telemetry_altitudeMeters_IsConstraintValid(const Telemetry_altitudeMeters* pVal, int* pErrCode);

#define ERR_TELEMETRY_VELOCITYHORIZONTALKILOMETERSPERHOUR		201  /*(0..512)*/
flag Telemetry_velocityHorizontalKilometersPerHour_IsConstraintValid(const Telemetry_velocityHorizontalKilometersPerHour* pVal, int* pErrCode);

#define ERR_TELEMETRY_GNSSSATELLITESVISIBLE		206  /*(0..31)*/
flag Telemetry_gnssSatellitesVisible_IsConstraintValid(const Telemetry_gnssSatellitesVisible* pVal, int* pErrCode);

#define ERR_TELEMETRY_ASCENTRATECENTIMETERSPERSECOND		211  /*(-32767..32767)*/
flag Telemetry_ascentRateCentimetersPerSecond_IsConstraintValid(const Telemetry_ascentRateCentimetersPerSecond* pVal, int* pErrCode);

#define ERR_TELEMETRY_PRESSUREHPA_X10		216  /*(0..12000)*/
flag Telemetry_pressurehPa_x10_IsConstraintValid(const Telemetry_pressurehPa_x10* pVal, int* pErrCode);

#define ERR_TELEMETRY_HUMIDITYPERCENTAGE		226  /*(0..100)*/
flag Telemetry_humidityPercentage_IsConstraintValid(const Telemetry_humidityPercentage* pVal, int* pErrCode);

#define ERR_TELEMETRY_COUNTS		241  /*(SIZE(1..8))*/
#define ERR_TELEMETRY_COUNTS_ELM		236  /**/
flag Telemetry_counts_IsConstraintValid(const Telemetry_counts* pVal, int* pErrCode);

#define ERR_TELEMETRY_CUSTOMDATA		256  /*(SIZE (0..255))*/
flag Telemetry_customData_IsConstraintValid(const Telemetry_customData* pVal, int* pErrCode);

#define ERR_TELEMETRY		261  /**/
#define ERR_TELEMETRY_EXTENSIONMARKERFORASN1CC		161  /**/
#define ERR_TELEMETRY_EXTRASENSORS		196  /**/
#define ERR_TELEMETRY_TEMPERATURECELSIUS_X10		221  /**/
#define ERR_TELEMETRY_MILLIVOLTS		231  /**/
#define ERR_TELEMETRY_GNSSPOWERSAVESTATE_2		251  /**/
flag Telemetry_IsConstraintValid(const Telemetry* pVal, int* pErrCode);

void Telemetry_payloadCallsign_Initialize(Telemetry_payloadCallsign pVal);
void Telemetry_sequenceNumber_Initialize(Telemetry_sequenceNumber* pVal);
void Telemetry_timeOfDaySeconds_Initialize(Telemetry_timeOfDaySeconds* pVal);
void Telemetry_latitude_Initialize(Telemetry_latitude* pVal);
void Telemetry_longitude_Initialize(Telemetry_longitude* pVal);
void Telemetry_altitudeMeters_Initialize(Telemetry_altitudeMeters* pVal);
void Telemetry_velocityHorizontalKilometersPerHour_Initialize(Telemetry_velocityHorizontalKilometersPerHour* pVal);
void Telemetry_gnssSatellitesVisible_Initialize(Telemetry_gnssSatellitesVisible* pVal);
void Telemetry_ascentRateCentimetersPerSecond_Initialize(Telemetry_ascentRateCentimetersPerSecond* pVal);
void Telemetry_pressurehPa_x10_Initialize(Telemetry_pressurehPa_x10* pVal);
void Telemetry_humidityPercentage_Initialize(Telemetry_humidityPercentage* pVal);
void Telemetry_counts_Initialize(Telemetry_counts* pVal);
void Telemetry_customData_Initialize(Telemetry_customData* pVal);
void Telemetry_Initialize(Telemetry* pVal);

#define ERR_UPER_ENCODE_TELEMETRY		262  /**/
#define ERR_UPER_ENCODE_TELEMETRY_EXTENSIONMARKERFORASN1CC		162  /**/
#define ERR_UPER_ENCODE_TELEMETRY_PAYLOADCALLSIGN		167  /**/
#define ERR_UPER_ENCODE_TELEMETRY_SEQUENCENUMBER		172  /**/
#define ERR_UPER_ENCODE_TELEMETRY_TIMEOFDAYSECONDS		177  /**/
#define ERR_UPER_ENCODE_TELEMETRY_LATITUDE		182  /**/
#define ERR_UPER_ENCODE_TELEMETRY_LONGITUDE		187  /**/
#define ERR_UPER_ENCODE_TELEMETRY_ALTITUDEMETERS		192  /**/
#define ERR_UPER_ENCODE_TELEMETRY_EXTRASENSORS		197  /**/
#define ERR_UPER_ENCODE_TELEMETRY_VELOCITYHORIZONTALKILOMETERSPERHOUR		202  /**/
#define ERR_UPER_ENCODE_TELEMETRY_GNSSSATELLITESVISIBLE		207  /**/
#define ERR_UPER_ENCODE_TELEMETRY_ASCENTRATECENTIMETERSPERSECOND		212  /**/
#define ERR_UPER_ENCODE_TELEMETRY_PRESSUREHPA_X10		217  /**/
#define ERR_UPER_ENCODE_TELEMETRY_TEMPERATURECELSIUS_X10		222  /**/
#define ERR_UPER_ENCODE_TELEMETRY_HUMIDITYPERCENTAGE		227  /**/
#define ERR_UPER_ENCODE_TELEMETRY_MILLIVOLTS		232  /**/
#define ERR_UPER_ENCODE_TELEMETRY_COUNTS		242  /**/
#define ERR_UPER_ENCODE_TELEMETRY_COUNTS_ELM		237  /**/
#define ERR_UPER_ENCODE_TELEMETRY_GNSSPOWERSAVESTATE_2		252  /**/
#define ERR_UPER_ENCODE_TELEMETRY_CUSTOMDATA		257  /**/
#define Telemetry_REQUIRED_BYTES_FOR_ENCODING       1336
#define Telemetry_REQUIRED_BITS_FOR_ENCODING        10687

flag Telemetry_Encode(const Telemetry* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_TELEMETRY		263  /**/
#define ERR_UPER_DECODE_TELEMETRY_EXTENSIONMARKERFORASN1CC		163  /**/
#define ERR_UPER_DECODE_TELEMETRY_PAYLOADCALLSIGN		168  /**/
#define ERR_UPER_DECODE_TELEMETRY_SEQUENCENUMBER		173  /**/
#define ERR_UPER_DECODE_TELEMETRY_TIMEOFDAYSECONDS		178  /**/
#define ERR_UPER_DECODE_TELEMETRY_LATITUDE		183  /**/
#define ERR_UPER_DECODE_TELEMETRY_LONGITUDE		188  /**/
#define ERR_UPER_DECODE_TELEMETRY_ALTITUDEMETERS		193  /**/
#define ERR_UPER_DECODE_TELEMETRY_EXTRASENSORS		198  /**/
#define ERR_UPER_DECODE_TELEMETRY_VELOCITYHORIZONTALKILOMETERSPERHOUR		203  /**/
#define ERR_UPER_DECODE_TELEMETRY_GNSSSATELLITESVISIBLE		208  /**/
#define ERR_UPER_DECODE_TELEMETRY_ASCENTRATECENTIMETERSPERSECOND		213  /**/
#define ERR_UPER_DECODE_TELEMETRY_PRESSUREHPA_X10		218  /**/
#define ERR_UPER_DECODE_TELEMETRY_TEMPERATURECELSIUS_X10		223  /**/
#define ERR_UPER_DECODE_TELEMETRY_HUMIDITYPERCENTAGE		228  /**/
#define ERR_UPER_DECODE_TELEMETRY_MILLIVOLTS		233  /**/
#define ERR_UPER_DECODE_TELEMETRY_COUNTS		243  /**/
#define ERR_UPER_DECODE_TELEMETRY_COUNTS_ELM		238  /**/
#define ERR_UPER_DECODE_TELEMETRY_GNSSPOWERSAVESTATE_2		253  /**/
#define ERR_UPER_DECODE_TELEMETRY_CUSTOMDATA		258  /**/
flag Telemetry_Decode(Telemetry* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
