/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"

#include "HorusBinaryV3.h"


flag BitFlags_IsConstraintValid(const BitFlags* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void BitFlags_Initialize(BitFlags* pVal)
{
	(void)pVal;


	/*set b0 */
	pVal->b0 = FALSE;
	/*set b1 */
	pVal->b1 = FALSE;
	/*set b2 */
	pVal->b2 = FALSE;
	/*set b3 */
	pVal->b3 = FALSE;
	/*set b4 */
	pVal->b4 = FALSE;
	/*set b5 */
	pVal->b5 = FALSE;
	/*set b6 */
	pVal->b6 = FALSE;
	/*set b7 */
	pVal->b7 = FALSE;
}

flag BitFlags_Encode(const BitFlags* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? BitFlags_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode b0 */
	    BitStream_AppendBit(pBitStrm,pVal->b0);
	    if (ret) {
	        /*Encode b1 */
	        BitStream_AppendBit(pBitStrm,pVal->b1);
	        if (ret) {
	            /*Encode b2 */
	            BitStream_AppendBit(pBitStrm,pVal->b2);
	            if (ret) {
	                /*Encode b3 */
	                BitStream_AppendBit(pBitStrm,pVal->b3);
	                if (ret) {
	                    /*Encode b4 */
	                    BitStream_AppendBit(pBitStrm,pVal->b4);
	                    if (ret) {
	                        /*Encode b5 */
	                        BitStream_AppendBit(pBitStrm,pVal->b5);
	                        if (ret) {
	                            /*Encode b6 */
	                            BitStream_AppendBit(pBitStrm,pVal->b6);
	                            if (ret) {
	                                /*Encode b7 */
	                                BitStream_AppendBit(pBitStrm,pVal->b7);
	                            }   /*COVERAGE_IGNORE*/
	                        }   /*COVERAGE_IGNORE*/
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BitFlags_Decode(BitFlags* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode b0 */
	ret = BitStream_ReadBit(pBitStrm, (&(pVal->b0)));
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_BITFLAGS_B0;
	if (ret) {
	    /*Decode b1 */
	    ret = BitStream_ReadBit(pBitStrm, (&(pVal->b1)));
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_BITFLAGS_B1;
	    if (ret) {
	        /*Decode b2 */
	        ret = BitStream_ReadBit(pBitStrm, (&(pVal->b2)));
	        *pErrCode = ret ? 0 : ERR_UPER_DECODE_BITFLAGS_B2;
	        if (ret) {
	            /*Decode b3 */
	            ret = BitStream_ReadBit(pBitStrm, (&(pVal->b3)));
	            *pErrCode = ret ? 0 : ERR_UPER_DECODE_BITFLAGS_B3;
	            if (ret) {
	                /*Decode b4 */
	                ret = BitStream_ReadBit(pBitStrm, (&(pVal->b4)));
	                *pErrCode = ret ? 0 : ERR_UPER_DECODE_BITFLAGS_B4;
	                if (ret) {
	                    /*Decode b5 */
	                    ret = BitStream_ReadBit(pBitStrm, (&(pVal->b5)));
	                    *pErrCode = ret ? 0 : ERR_UPER_DECODE_BITFLAGS_B5;
	                    if (ret) {
	                        /*Decode b6 */
	                        ret = BitStream_ReadBit(pBitStrm, (&(pVal->b6)));
	                        *pErrCode = ret ? 0 : ERR_UPER_DECODE_BITFLAGS_B6;
	                        if (ret) {
	                            /*Decode b7 */
	                            ret = BitStream_ReadBit(pBitStrm, (&(pVal->b7)));
	                            *pErrCode = ret ? 0 : ERR_UPER_DECODE_BITFLAGS_B7;
	                        }   /*COVERAGE_IGNORE*/
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && BitFlags_IsConstraintValid(pVal, pErrCode);
}


flag CustomFieldValues_horusStr_CharsAreValid_0(const char* str)
{
    flag ret=TRUE;
    int i=0;

    while ((str[i] != '\0') && ret) {
        ret = ret && (strchr("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_ +/=-.", str[i]));
        i = i + 1;
    }
    return ret;
}
flag CustomFieldValues_horusStr_IsConstraintValid(const CustomFieldValues_horusStr pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = (CustomFieldValues_horusStr_CharsAreValid_0(pVal) && (strlen(pVal) <= 255));
    *pErrCode = ret ? 0 :  ERR_CUSTOMFIELDVALUES_HORUSSTR;

	return ret;
}

flag CustomFieldValues_horusInt_IsConstraintValid(const CustomFieldValues_horusInt* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((1 <= pVal->nCount) && (pVal->nCount <= 4));
    *pErrCode = ret ? 0 :  ERR_CUSTOMFIELDVALUES_HORUSINT;

	return ret;
}

flag CustomFieldValues_horusReal_IsConstraintValid(const CustomFieldValues_horusReal* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((1 <= pVal->nCount) && (pVal->nCount <= 4));
    *pErrCode = ret ? 0 :  ERR_CUSTOMFIELDVALUES_HORUSREAL;

	return ret;
}

flag CustomFieldValues_IsConstraintValid(const CustomFieldValues* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case horusStr_PRESENT : 
            ret = CustomFieldValues_horusStr_IsConstraintValid(pVal->u.horusStr, pErrCode);
            break;          
        case horusInt_PRESENT : 
            ret = CustomFieldValues_horusInt_IsConstraintValid((&(pVal->u.horusInt)), pErrCode);
            break;          
        case horusReal_PRESENT : 
            ret = CustomFieldValues_horusReal_IsConstraintValid((&(pVal->u.horusReal)), pErrCode);
            break;          
        case horusBool_PRESENT : 
            ret = BitFlags_IsConstraintValid((&(pVal->u.horusBool)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_CUSTOMFIELDVALUES;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

void CustomFieldValues_horusStr_Initialize(CustomFieldValues_horusStr pVal)
{
	(void)pVal;


	memset(pVal, ' ', 255);
	pVal[255] = 0;

}
void CustomFieldValues_horusInt_Initialize(CustomFieldValues_horusInt* pVal)
{
	(void)pVal;

    int i1;

	i1 = 0;
	while (i1< 4) {
	    pVal->arr[i1] = 0LL;
	    i1 = i1 + 1;
	}
	pVal->nCount = 1;
}
void CustomFieldValues_horusReal_Initialize(CustomFieldValues_horusReal* pVal)
{
	(void)pVal;

    int i1;

	i1 = 0;
	while (i1< 4) {
	    pVal->arr[i1] = 0.0000000000000000000E+000;
	    i1 = i1 + 1;
	}
	pVal->nCount = 1;
}
void CustomFieldValues_Initialize(CustomFieldValues* pVal)
{
	(void)pVal;


	pVal->kind = horusStr_PRESENT;
	CustomFieldValues_horusStr_Initialize(pVal->u.horusStr);
}

flag CustomFieldValues_Encode(const CustomFieldValues* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	int i1;
	asn1SccSint nStringLength;
	*pErrCode = 0;
	ret = bCheckConstraints ? CustomFieldValues_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch(pVal->kind)
	    {
	    case horusStr_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 3);
	    	nStringLength = strlen(pVal->u.horusStr);
	    	/*ret = nStringLength >= 0 && nStringLength <= 255;*/
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, nStringLength, 0, 255);
	    	for(i1=0; (i1 < (int)nStringLength) && ret; i1++)
	    	{
	    		static byte allowedCharSet[] = {0x20,0x2B,0x2D,0x2E,0x2F,0x30,0x31,0x32,0x33,0x34,
	    		                                0x35,0x36,0x37,0x38,0x39,0x3D,0x41,0x42,0x43,0x44,
	    		                                0x45,0x46,0x47,0x48,0x49,0x4A,0x4B,0x4C,0x4D,0x4E,
	    		                                0x4F,0x50,0x51,0x52,0x53,0x54,0x55,0x56,0x57,0x58,
	    		                                0x59,0x5A,0x5F,0x61,0x62,0x63,0x64,0x65,0x66,0x67,
	    		                                0x68,0x69,0x6A,0x6B,0x6C,0x6D,0x6E,0x6F,0x70,0x71,
	    		                                0x72,0x73,0x74,0x75,0x76,0x77,0x78,0x79,0x7A};
	    		int charIndex = GetCharIndex(pVal->u.horusStr[i1], allowedCharSet, 69);
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, charIndex, 0, 68);
	    	}

	    	break;
	    case horusInt_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 3);
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->u.horusInt.nCount, 1, 4);
	    	for(i1=0; (i1 < (int)pVal->u.horusInt.nCount) && ret; i1++)
	    	{
	    		BitStream_EncodeUnConstraintWholeNumber(pBitStrm, pVal->u.horusInt.arr[i1]);
	    	}
	    	break;
	    case horusReal_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 3);
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->u.horusReal.nCount, 1, 4);
	    	for(i1=0; (i1 < (int)pVal->u.horusReal.nCount) && ret; i1++)
	    	{
	    		BitStream_EncodeReal(pBitStrm, pVal->u.horusReal.arr[i1]);
	    	}
	    	break;
	    case horusBool_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 3);
	    	ret = BitFlags_Encode((&(pVal->u.horusBool)), pBitStrm, pErrCode, FALSE);
	    	break;
	    default:                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_ENCODE_CUSTOMFIELDVALUES;         /*COVERAGE_IGNORE*/
	        ret = FALSE;                    /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag CustomFieldValues_Decode(CustomFieldValues* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint CustomFieldValues_index_tmp;
	int i1;
	asn1SccSint nStringLength;
	asn1SccSint nCount;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &CustomFieldValues_index_tmp, 0, 3);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_CUSTOMFIELDVALUES;
	if (ret) {
	    switch(CustomFieldValues_index_tmp)
	    {
	    case 0:
	    	pVal->kind = horusStr_PRESENT;
	    	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nStringLength, 0, 255);
	    	for(i1=0; (i1 < (int)nStringLength) && ret; i1++)
	    	{
	    		static byte allowedCharSet[] = {0x20,0x2B,0x2D,0x2E,0x2F,0x30,0x31,0x32,0x33,0x34,
	    		                                0x35,0x36,0x37,0x38,0x39,0x3D,0x41,0x42,0x43,0x44,
	    		                                0x45,0x46,0x47,0x48,0x49,0x4A,0x4B,0x4C,0x4D,0x4E,
	    		                                0x4F,0x50,0x51,0x52,0x53,0x54,0x55,0x56,0x57,0x58,
	    		                                0x59,0x5A,0x5F,0x61,0x62,0x63,0x64,0x65,0x66,0x67,
	    		                                0x68,0x69,0x6A,0x6B,0x6C,0x6D,0x6E,0x6F,0x70,0x71,
	    		                                0x72,0x73,0x74,0x75,0x76,0x77,0x78,0x79,0x7A};
	    		asn1SccSint charIndex = 0;
	    		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &charIndex, 0, 68);
	    		*pErrCode = ret ? 0 : ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSSTR;
	    		if (ret && (charIndex < 0 || charIndex > 68)) { ret = FALSE; *pErrCode = ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSSTR; }
	    		pVal->u.horusStr[i1] = ret ? allowedCharSet[charIndex] : '\0' ;
	    	}
	    	pVal->u.horusStr[nStringLength] = 0x0;
	    	break;
	    case 1:
	    	pVal->kind = horusInt_PRESENT;
	    	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 4);
	    	*pErrCode = ret ? 0 : ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSINT;
	    	pVal->u.horusInt.nCount = (long)nCount;
	    	for(i1=0; (i1 < (int)pVal->u.horusInt.nCount) && ret; i1++)
	    	{
	    		ret = BitStream_DecodeUnConstraintWholeNumber(pBitStrm, (&(pVal->u.horusInt.arr[i1])));   
	    		*pErrCode = ret ? 0 : ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSINT_ELM;                               
	    	}
	    	break;
	    case 2:
	    	pVal->kind = horusReal_PRESENT;
	    	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 4);
	    	*pErrCode = ret ? 0 : ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSREAL;
	    	pVal->u.horusReal.nCount = (long)nCount;
	    	for(i1=0; (i1 < (int)pVal->u.horusReal.nCount) && ret; i1++)
	    	{
	    		ret = BitStream_DecodeReal(pBitStrm, (&(pVal->u.horusReal.arr[i1])));
	    		*pErrCode = ret ? 0 : ERR_UPER_DECODE_CUSTOMFIELDVALUES_HORUSREAL_ELM;
	    	}
	    	break;
	    case 3:
	    	pVal->kind = horusBool_PRESENT;
	    	ret = BitFlags_Decode((&(pVal->u.horusBool)), pBitStrm, pErrCode);
	    	break;
	    default:                        /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_DECODE_CUSTOMFIELDVALUES;     /*COVERAGE_IGNORE*/
	        ret = FALSE;                /*COVERAGE_IGNORE*/
	    }
	}  /*COVERAGE_IGNORE*/

	return ret  && CustomFieldValues_IsConstraintValid(pVal, pErrCode);
}


flag AdditionalSensorType_name_CharsAreValid_0(const char* str)
{
    flag ret=TRUE;
    int i=0;

    while ((str[i] != '\0') && ret) {
        ret = ret && (strchr("abcdefghijklmnopqrstuvwxyz0123456789-", str[i]));
        i = i + 1;
    }
    return ret;
}
flag AdditionalSensorType_name_IsConstraintValid(const AdditionalSensorType_name pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = (AdditionalSensorType_name_CharsAreValid_0(pVal) && ((1 <= strlen(pVal)) && (strlen(pVal) <= 20)));
    *pErrCode = ret ? 0 :  ERR_ADDITIONALSENSORTYPE_NAME;

	return ret;
}

flag AdditionalSensorType_IsConstraintValid(const AdditionalSensorType* pVal, int* pErrCode)
{
    flag ret = TRUE;
    if (pVal->exist.name) {
    	ret = AdditionalSensorType_name_IsConstraintValid(pVal->name, pErrCode);
    }
    if (ret) {
        if (pVal->exist.values) {
        	ret = CustomFieldValues_IsConstraintValid((&(pVal->values)), pErrCode);
        }
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void AdditionalSensorType_name_Initialize(AdditionalSensorType_name pVal)
{
	(void)pVal;


	memset(pVal, '-', 20);
	pVal[20] = 0;

}
void AdditionalSensorType_Initialize(AdditionalSensorType* pVal)
{
	(void)pVal;


	/*set name */
	pVal->exist.name = 1;
	AdditionalSensorType_name_Initialize(pVal->name);
	/*set values */
	pVal->exist.values = 1;
	CustomFieldValues_Initialize((&(pVal->values)));
}

flag AdditionalSensorType_Encode(const AdditionalSensorType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	int i1;
	asn1SccSint nStringLength;
	*pErrCode = 0;
	ret = bCheckConstraints ? AdditionalSensorType_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,pVal->exist.name);
	    if (ret) {
	        BitStream_AppendBit(pBitStrm,pVal->exist.values);
	        if (ret) {
	            /*Encode name */
	            if (pVal->exist.name) {
	            	nStringLength = strlen(pVal->name);
	            	/*ret = nStringLength >= 1 && nStringLength <= 20;*/
	            	BitStream_EncodeConstraintWholeNumber(pBitStrm, nStringLength, 1, 20);
	            	for(i1=0; (i1 < (int)nStringLength) && ret; i1++)
	            	{
	            		static byte allowedCharSet[] = {0x2D,0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,
	            		                                0x39,0x61,0x62,0x63,0x64,0x65,0x66,0x67,0x68,0x69,
	            		                                0x6A,0x6B,0x6C,0x6D,0x6E,0x6F,0x70,0x71,0x72,0x73,
	            		                                0x74,0x75,0x76,0x77,0x78,0x79,0x7A};
	            		int charIndex = GetCharIndex(pVal->name[i1], allowedCharSet, 37);
	            		BitStream_EncodeConstraintWholeNumber(pBitStrm, charIndex, 0, 36);
	            	}

	            }
	            if (ret) {
	                /*Encode values */
	                if (pVal->exist.values) {
	                	ret = CustomFieldValues_Encode((&(pVal->values)), pBitStrm, pErrCode, FALSE);
	                }
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag AdditionalSensorType_Decode(AdditionalSensorType* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	flag presenceBit;
	int i1;
	asn1SccSint nStringLength;

	ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	pVal->exist.name = presenceBit == 0 ? 0 : 1;
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_ADDITIONALSENSORTYPE;
	if (ret) {
	    ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	    pVal->exist.values = presenceBit == 0 ? 0 : 1;
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_ADDITIONALSENSORTYPE;
	    if (ret) {
	        /*Decode name */
	        if (pVal->exist.name) {
	        	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nStringLength, 1, 20);
	        	for(i1=0; (i1 < (int)nStringLength) && ret; i1++)
	        	{
	        		static byte allowedCharSet[] = {0x2D,0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,
	        		                                0x39,0x61,0x62,0x63,0x64,0x65,0x66,0x67,0x68,0x69,
	        		                                0x6A,0x6B,0x6C,0x6D,0x6E,0x6F,0x70,0x71,0x72,0x73,
	        		                                0x74,0x75,0x76,0x77,0x78,0x79,0x7A};
	        		asn1SccSint charIndex = 0;
	        		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &charIndex, 0, 36);
	        		*pErrCode = ret ? 0 : ERR_UPER_DECODE_ADDITIONALSENSORTYPE_NAME;
	        		if (ret && (charIndex < 0 || charIndex > 36)) { ret = FALSE; *pErrCode = ERR_UPER_DECODE_ADDITIONALSENSORTYPE_NAME; }
	        		pVal->name[i1] = ret ? allowedCharSet[charIndex] : '\0' ;
	        	}
	        	pVal->name[nStringLength] = 0x0;
	        }
	        if (ret) {
	            /*Decode values */
	            if (pVal->exist.values) {
	            	ret = CustomFieldValues_Decode((&(pVal->values)), pBitStrm, pErrCode);
	            }
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && AdditionalSensorType_IsConstraintValid(pVal, pErrCode);
}


flag AdditionalSensors_IsConstraintValid(const AdditionalSensors* pVal, int* pErrCode)
{
    flag ret = TRUE;
    int i1;
    ret = ((1 <= pVal->nCount) && (pVal->nCount <= 4));
    *pErrCode = ret ? 0 :  ERR_ADDITIONALSENSORS;
    if (ret) {
        for(i1 = 0; ret && i1 < pVal->nCount; i1++)
        {
        	ret = AdditionalSensorType_IsConstraintValid((&(pVal->arr[i1])), pErrCode);
        }
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void AdditionalSensors_Initialize(AdditionalSensors* pVal)
{
	(void)pVal;

    int i1;

	i1 = 0;
	while (i1< 4) {
	    AdditionalSensorType_Initialize((&(pVal->arr[i1])));
	    i1 = i1 + 1;
	}
	pVal->nCount = 1;
}

flag AdditionalSensors_Encode(const AdditionalSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	int i1;
	*pErrCode = 0;
	ret = bCheckConstraints ? AdditionalSensors_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 4);
	    for(i1=0; (i1 < (int)pVal->nCount) && ret; i1++)
	    {
	    	ret = AdditionalSensorType_Encode((&(pVal->arr[i1])), pBitStrm, pErrCode, FALSE);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag AdditionalSensors_Decode(AdditionalSensors* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	int i1;
	asn1SccSint nCount;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 4);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_ADDITIONALSENSORS;
	pVal->nCount = (long)nCount;
	for(i1=0; (i1 < (int)pVal->nCount) && ret; i1++)
	{
		ret = AdditionalSensorType_Decode((&(pVal->arr[i1])), pBitStrm, pErrCode);
	}

	return ret  && AdditionalSensors_IsConstraintValid(pVal, pErrCode);
}


flag TemperatureSensors_internal_IsConstraintValid(const TemperatureSensors_internal* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-1023LL <= (*(pVal))) && ((*(pVal)) <= 1023LL));
    *pErrCode = ret ? 0 :  ERR_TEMPERATURESENSORS_INTERNAL;

	return ret;
}

flag TemperatureSensors_external_IsConstraintValid(const TemperatureSensors_external* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-1023LL <= (*(pVal))) && ((*(pVal)) <= 1023LL));
    *pErrCode = ret ? 0 :  ERR_TEMPERATURESENSORS_EXTERNAL;

	return ret;
}

flag TemperatureSensors_custom1_IsConstraintValid(const TemperatureSensors_custom1* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-1023LL <= (*(pVal))) && ((*(pVal)) <= 1023LL));
    *pErrCode = ret ? 0 :  ERR_TEMPERATURESENSORS_CUSTOM1;

	return ret;
}

flag TemperatureSensors_custom2_IsConstraintValid(const TemperatureSensors_custom2* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-1023LL <= (*(pVal))) && ((*(pVal)) <= 1023LL));
    *pErrCode = ret ? 0 :  ERR_TEMPERATURESENSORS_CUSTOM2;

	return ret;
}

flag TemperatureSensors_IsConstraintValid(const TemperatureSensors* pVal, int* pErrCode)
{
    flag ret = TRUE;
    if (pVal->exist.internal) {
    	ret = TemperatureSensors_internal_IsConstraintValid((&(pVal->internal)), pErrCode);
    }
    if (ret) {
        if (pVal->exist.external) {
        	ret = TemperatureSensors_external_IsConstraintValid((&(pVal->external)), pErrCode);
        }
        if (ret) {
            if (pVal->exist.custom1) {
            	ret = TemperatureSensors_custom1_IsConstraintValid((&(pVal->custom1)), pErrCode);
            }
            if (ret) {
                if (pVal->exist.custom2) {
                	ret = TemperatureSensors_custom2_IsConstraintValid((&(pVal->custom2)), pErrCode);
                }
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void TemperatureSensors_internal_Initialize(TemperatureSensors_internal* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void TemperatureSensors_external_Initialize(TemperatureSensors_external* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void TemperatureSensors_custom1_Initialize(TemperatureSensors_custom1* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void TemperatureSensors_custom2_Initialize(TemperatureSensors_custom2* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void TemperatureSensors_Initialize(TemperatureSensors* pVal)
{
	(void)pVal;


	/*set internal */
	pVal->exist.internal = 1;
	TemperatureSensors_internal_Initialize((&(pVal->internal)));
	/*set external */
	pVal->exist.external = 1;
	TemperatureSensors_external_Initialize((&(pVal->external)));
	/*set custom1 */
	pVal->exist.custom1 = 1;
	TemperatureSensors_custom1_Initialize((&(pVal->custom1)));
	/*set custom2 */
	pVal->exist.custom2 = 1;
	TemperatureSensors_custom2_Initialize((&(pVal->custom2)));
}

flag TemperatureSensors_Encode(const TemperatureSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? TemperatureSensors_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,pVal->exist.internal);
	    if (ret) {
	        BitStream_AppendBit(pBitStrm,pVal->exist.external);
	        if (ret) {
	            BitStream_AppendBit(pBitStrm,pVal->exist.custom1);
	            if (ret) {
	                BitStream_AppendBit(pBitStrm,pVal->exist.custom2);
	                if (ret) {
	                    /*Encode internal */
	                    if (pVal->exist.internal) {
	                    	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->internal, -1023, 1023);
	                    }
	                    if (ret) {
	                        /*Encode external */
	                        if (pVal->exist.external) {
	                        	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->external, -1023, 1023);
	                        }
	                        if (ret) {
	                            /*Encode custom1 */
	                            if (pVal->exist.custom1) {
	                            	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->custom1, -1023, 1023);
	                            }
	                            if (ret) {
	                                /*Encode custom2 */
	                                if (pVal->exist.custom2) {
	                                	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->custom2, -1023, 1023);
	                                }
	                            }   /*COVERAGE_IGNORE*/
	                        }   /*COVERAGE_IGNORE*/
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag TemperatureSensors_Decode(TemperatureSensors* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	flag presenceBit;

	ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	pVal->exist.internal = presenceBit == 0 ? 0 : 1;
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TEMPERATURESENSORS;
	if (ret) {
	    ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	    pVal->exist.external = presenceBit == 0 ? 0 : 1;
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_TEMPERATURESENSORS;
	    if (ret) {
	        ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	        pVal->exist.custom1 = presenceBit == 0 ? 0 : 1;
	        *pErrCode = ret ? 0 : ERR_UPER_DECODE_TEMPERATURESENSORS;
	        if (ret) {
	            ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	            pVal->exist.custom2 = presenceBit == 0 ? 0 : 1;
	            *pErrCode = ret ? 0 : ERR_UPER_DECODE_TEMPERATURESENSORS;
	            if (ret) {
	                /*Decode internal */
	                if (pVal->exist.internal) {
	                	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->internal)), -1023, 1023);
	                	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TEMPERATURESENSORS_INTERNAL;
	                }
	                if (ret) {
	                    /*Decode external */
	                    if (pVal->exist.external) {
	                    	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->external)), -1023, 1023);
	                    	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TEMPERATURESENSORS_EXTERNAL;
	                    }
	                    if (ret) {
	                        /*Decode custom1 */
	                        if (pVal->exist.custom1) {
	                        	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->custom1)), -1023, 1023);
	                        	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TEMPERATURESENSORS_CUSTOM1;
	                        }
	                        if (ret) {
	                            /*Decode custom2 */
	                            if (pVal->exist.custom2) {
	                            	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->custom2)), -1023, 1023);
	                            	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TEMPERATURESENSORS_CUSTOM2;
	                            }
	                        }   /*COVERAGE_IGNORE*/
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && TemperatureSensors_IsConstraintValid(pVal, pErrCode);
}


flag MilliVoltSensors_battery_IsConstraintValid(const MilliVoltSensors_battery* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 16383UL);
    *pErrCode = ret ? 0 :  ERR_MILLIVOLTSENSORS_BATTERY;

	return ret;
}

flag MilliVoltSensors_solar_IsConstraintValid(const MilliVoltSensors_solar* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 16383UL);
    *pErrCode = ret ? 0 :  ERR_MILLIVOLTSENSORS_SOLAR;

	return ret;
}

flag MilliVoltSensors_custom1_IsConstraintValid(const MilliVoltSensors_custom1* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 16383UL);
    *pErrCode = ret ? 0 :  ERR_MILLIVOLTSENSORS_CUSTOM1;

	return ret;
}

flag MilliVoltSensors_custom2_IsConstraintValid(const MilliVoltSensors_custom2* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 16383UL);
    *pErrCode = ret ? 0 :  ERR_MILLIVOLTSENSORS_CUSTOM2;

	return ret;
}

flag MilliVoltSensors_IsConstraintValid(const MilliVoltSensors* pVal, int* pErrCode)
{
    flag ret = TRUE;
    if (pVal->exist.battery) {
    	ret = MilliVoltSensors_battery_IsConstraintValid((&(pVal->battery)), pErrCode);
    }
    if (ret) {
        if (pVal->exist.solar) {
        	ret = MilliVoltSensors_solar_IsConstraintValid((&(pVal->solar)), pErrCode);
        }
        if (ret) {
            if (pVal->exist.custom1) {
            	ret = MilliVoltSensors_custom1_IsConstraintValid((&(pVal->custom1)), pErrCode);
            }
            if (ret) {
                if (pVal->exist.custom2) {
                	ret = MilliVoltSensors_custom2_IsConstraintValid((&(pVal->custom2)), pErrCode);
                }
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void MilliVoltSensors_battery_Initialize(MilliVoltSensors_battery* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void MilliVoltSensors_solar_Initialize(MilliVoltSensors_solar* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void MilliVoltSensors_custom1_Initialize(MilliVoltSensors_custom1* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void MilliVoltSensors_custom2_Initialize(MilliVoltSensors_custom2* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void MilliVoltSensors_Initialize(MilliVoltSensors* pVal)
{
	(void)pVal;


	/*set battery */
	pVal->exist.battery = 1;
	MilliVoltSensors_battery_Initialize((&(pVal->battery)));
	/*set solar */
	pVal->exist.solar = 1;
	MilliVoltSensors_solar_Initialize((&(pVal->solar)));
	/*set custom1 */
	pVal->exist.custom1 = 1;
	MilliVoltSensors_custom1_Initialize((&(pVal->custom1)));
	/*set custom2 */
	pVal->exist.custom2 = 1;
	MilliVoltSensors_custom2_Initialize((&(pVal->custom2)));
}

flag MilliVoltSensors_Encode(const MilliVoltSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? MilliVoltSensors_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,pVal->exist.battery);
	    if (ret) {
	        BitStream_AppendBit(pBitStrm,pVal->exist.solar);
	        if (ret) {
	            BitStream_AppendBit(pBitStrm,pVal->exist.custom1);
	            if (ret) {
	                BitStream_AppendBit(pBitStrm,pVal->exist.custom2);
	                if (ret) {
	                    /*Encode battery */
	                    if (pVal->exist.battery) {
	                    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->battery, 0, 16383);
	                    }
	                    if (ret) {
	                        /*Encode solar */
	                        if (pVal->exist.solar) {
	                        	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->solar, 0, 16383);
	                        }
	                        if (ret) {
	                            /*Encode custom1 */
	                            if (pVal->exist.custom1) {
	                            	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->custom1, 0, 16383);
	                            }
	                            if (ret) {
	                                /*Encode custom2 */
	                                if (pVal->exist.custom2) {
	                                	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->custom2, 0, 16383);
	                                }
	                            }   /*COVERAGE_IGNORE*/
	                        }   /*COVERAGE_IGNORE*/
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag MilliVoltSensors_Decode(MilliVoltSensors* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	flag presenceBit;

	ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	pVal->exist.battery = presenceBit == 0 ? 0 : 1;
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_MILLIVOLTSENSORS;
	if (ret) {
	    ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	    pVal->exist.solar = presenceBit == 0 ? 0 : 1;
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_MILLIVOLTSENSORS;
	    if (ret) {
	        ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	        pVal->exist.custom1 = presenceBit == 0 ? 0 : 1;
	        *pErrCode = ret ? 0 : ERR_UPER_DECODE_MILLIVOLTSENSORS;
	        if (ret) {
	            ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	            pVal->exist.custom2 = presenceBit == 0 ? 0 : 1;
	            *pErrCode = ret ? 0 : ERR_UPER_DECODE_MILLIVOLTSENSORS;
	            if (ret) {
	                /*Decode battery */
	                if (pVal->exist.battery) {
	                	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->battery)), 0, 16383);
	                	*pErrCode = ret ? 0 : ERR_UPER_DECODE_MILLIVOLTSENSORS_BATTERY;
	                }
	                if (ret) {
	                    /*Decode solar */
	                    if (pVal->exist.solar) {
	                    	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->solar)), 0, 16383);
	                    	*pErrCode = ret ? 0 : ERR_UPER_DECODE_MILLIVOLTSENSORS_SOLAR;
	                    }
	                    if (ret) {
	                        /*Decode custom1 */
	                        if (pVal->exist.custom1) {
	                        	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->custom1)), 0, 16383);
	                        	*pErrCode = ret ? 0 : ERR_UPER_DECODE_MILLIVOLTSENSORS_CUSTOM1;
	                        }
	                        if (ret) {
	                            /*Decode custom2 */
	                            if (pVal->exist.custom2) {
	                            	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->custom2)), 0, 16383);
	                            	*pErrCode = ret ? 0 : ERR_UPER_DECODE_MILLIVOLTSENSORS_CUSTOM2;
	                            }
	                        }   /*COVERAGE_IGNORE*/
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && MilliVoltSensors_IsConstraintValid(pVal, pErrCode);
}


flag GnssPowerSaveState_IsConstraintValid(const GnssPowerSaveState* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((((((*(pVal)) == psmNotActive)) || (((*(pVal)) == enabled)))) || (((*(pVal)) == acquisition)))) || (((*(pVal)) == tracking)))) || (((*(pVal)) == optimised)))) || (((*(pVal)) == inactive)));
    *pErrCode = ret ? 0 :  ERR_GNSSPOWERSAVESTATE;

	return ret;
}

void GnssPowerSaveState_Initialize(GnssPowerSaveState* pVal)
{
	(void)pVal;


	(*(pVal)) = psmNotActive;
}

flag GnssPowerSaveState_Encode(const GnssPowerSaveState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? GnssPowerSaveState_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal)))
	    {
	        case psmNotActive:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 5);
	        	break;
	        case enabled:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 5);
	        	break;
	        case acquisition:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 5);
	        	break;
	        case tracking:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 5);
	        	break;
	        case optimised:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 4, 0, 5);
	        	break;
	        case inactive:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 5, 0, 5);
	        	break;
	        default:                    /*COVERAGE_IGNORE*/
	    	    *pErrCode = ERR_UPER_ENCODE_GNSSPOWERSAVESTATE; /*COVERAGE_IGNORE*/
	    	    ret = FALSE;            /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag GnssPowerSaveState_Decode(GnssPowerSaveState* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	{
	    asn1SccSint enumIndex;
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 5);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_GNSSPOWERSAVESTATE;
	    if (ret) {
	        switch(enumIndex)
	        {
	            case 0:
	                (*(pVal)) = psmNotActive;
	                break;
	            case 1:
	                (*(pVal)) = enabled;
	                break;
	            case 2:
	                (*(pVal)) = acquisition;
	                break;
	            case 3:
	                (*(pVal)) = tracking;
	                break;
	            case 4:
	                (*(pVal)) = optimised;
	                break;
	            case 5:
	                (*(pVal)) = inactive;
	                break;
	            default:                        /*COVERAGE_IGNORE*/
		            *pErrCode = ERR_UPER_DECODE_GNSSPOWERSAVESTATE;     /*COVERAGE_IGNORE*/
		            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } else {
	        (*(pVal)) = psmNotActive;             /*COVERAGE_IGNORE*/
	    }
	}

	return ret  && GnssPowerSaveState_IsConstraintValid(pVal, pErrCode);
}


flag Telemetry_payloadCallsign_CharsAreValid_0(const char* str)
{
    flag ret=TRUE;
    int i=0;

    while ((str[i] != '\0') && ret) {
        ret = ret && (strchr("-/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", str[i]));
        i = i + 1;
    }
    return ret;
}
flag Telemetry_payloadCallsign_IsConstraintValid(const Telemetry_payloadCallsign pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = (Telemetry_payloadCallsign_CharsAreValid_0(pVal) && ((1 <= strlen(pVal)) && (strlen(pVal) <= 15)));
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_PAYLOADCALLSIGN;

	return ret;
}

flag Telemetry_sequenceNumber_IsConstraintValid(const Telemetry_sequenceNumber* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 65535UL);
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_SEQUENCENUMBER;

	return ret;
}

flag Telemetry_timeOfDaySeconds_IsConstraintValid(const Telemetry_timeOfDaySeconds* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-1LL <= (*(pVal))) && ((*(pVal)) <= 86400LL));
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_TIMEOFDAYSECONDS;

	return ret;
}

flag Telemetry_latitude_IsConstraintValid(const Telemetry_latitude* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-9000000LL <= (*(pVal))) && ((*(pVal)) <= 9000000LL));
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_LATITUDE;

	return ret;
}

flag Telemetry_longitude_IsConstraintValid(const Telemetry_longitude* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-18000000LL <= (*(pVal))) && ((*(pVal)) <= 18000000LL));
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_LONGITUDE;

	return ret;
}

flag Telemetry_altitudeMeters_IsConstraintValid(const Telemetry_altitudeMeters* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-1000LL <= (*(pVal))) && ((*(pVal)) <= 50000LL));
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_ALTITUDEMETERS;

	return ret;
}

flag Telemetry_velocityHorizontalKilometersPerHour_IsConstraintValid(const Telemetry_velocityHorizontalKilometersPerHour* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 512UL);
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_VELOCITYHORIZONTALKILOMETERSPERHOUR;

	return ret;
}

flag Telemetry_gnssSatellitesVisible_IsConstraintValid(const Telemetry_gnssSatellitesVisible* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 31UL);
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_GNSSSATELLITESVISIBLE;

	return ret;
}

flag Telemetry_ascentRateCentimetersPerSecond_IsConstraintValid(const Telemetry_ascentRateCentimetersPerSecond* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-32767LL <= (*(pVal))) && ((*(pVal)) <= 32767LL));
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_ASCENTRATECENTIMETERSPERSECOND;

	return ret;
}

flag Telemetry_pressurehPa_x10_IsConstraintValid(const Telemetry_pressurehPa_x10* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 12000UL);
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_PRESSUREHPA_X10;

	return ret;
}

flag Telemetry_humidityPercentage_IsConstraintValid(const Telemetry_humidityPercentage* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 100UL);
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_HUMIDITYPERCENTAGE;

	return ret;
}

flag Telemetry_counts_IsConstraintValid(const Telemetry_counts* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((1 <= pVal->nCount) && (pVal->nCount <= 8));
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_COUNTS;

	return ret;
}

flag Telemetry_customData_IsConstraintValid(const Telemetry_customData* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = (pVal->nCount <= 255);
    *pErrCode = ret ? 0 :  ERR_TELEMETRY_CUSTOMDATA;

	return ret;
}

flag Telemetry_IsConstraintValid(const Telemetry* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Telemetry_payloadCallsign_IsConstraintValid(pVal->payloadCallsign, pErrCode);
    if (ret) {
        ret = Telemetry_sequenceNumber_IsConstraintValid((&(pVal->sequenceNumber)), pErrCode);
        if (ret) {
            ret = Telemetry_timeOfDaySeconds_IsConstraintValid((&(pVal->timeOfDaySeconds)), pErrCode);
            if (ret) {
                ret = Telemetry_latitude_IsConstraintValid((&(pVal->latitude)), pErrCode);
                if (ret) {
                    ret = Telemetry_longitude_IsConstraintValid((&(pVal->longitude)), pErrCode);
                    if (ret) {
                        ret = Telemetry_altitudeMeters_IsConstraintValid((&(pVal->altitudeMeters)), pErrCode);
                        if (ret) {
                            if (pVal->exist.extraSensors) {
                            	ret = AdditionalSensors_IsConstraintValid((&(pVal->extraSensors)), pErrCode);
                            }
                            if (ret) {
                                if (pVal->exist.velocityHorizontalKilometersPerHour) {
                                	ret = Telemetry_velocityHorizontalKilometersPerHour_IsConstraintValid((&(pVal->velocityHorizontalKilometersPerHour)), pErrCode);
                                }
                                if (ret) {
                                    if (pVal->exist.gnssSatellitesVisible) {
                                    	ret = Telemetry_gnssSatellitesVisible_IsConstraintValid((&(pVal->gnssSatellitesVisible)), pErrCode);
                                    }
                                    if (ret) {
                                        if (pVal->exist.ascentRateCentimetersPerSecond) {
                                        	ret = Telemetry_ascentRateCentimetersPerSecond_IsConstraintValid((&(pVal->ascentRateCentimetersPerSecond)), pErrCode);
                                        }
                                        if (ret) {
                                            if (pVal->exist.pressurehPa_x10) {
                                            	ret = Telemetry_pressurehPa_x10_IsConstraintValid((&(pVal->pressurehPa_x10)), pErrCode);
                                            }
                                            if (ret) {
                                                if (pVal->exist.temperatureCelsius_x10) {
                                                	ret = TemperatureSensors_IsConstraintValid((&(pVal->temperatureCelsius_x10)), pErrCode);
                                                }
                                                if (ret) {
                                                    if (pVal->exist.humidityPercentage) {
                                                    	ret = Telemetry_humidityPercentage_IsConstraintValid((&(pVal->humidityPercentage)), pErrCode);
                                                    }
                                                    if (ret) {
                                                        if (pVal->exist.milliVolts) {
                                                        	ret = MilliVoltSensors_IsConstraintValid((&(pVal->milliVolts)), pErrCode);
                                                        }
                                                        if (ret) {
                                                            if (pVal->exist.counts) {
                                                            	ret = Telemetry_counts_IsConstraintValid((&(pVal->counts)), pErrCode);
                                                            }
                                                            if (ret) {
                                                                if (pVal->exist.gnssPowerSaveState) {
                                                                	ret = GnssPowerSaveState_IsConstraintValid((&(pVal->gnssPowerSaveState)), pErrCode);
                                                                }
                                                                if (ret) {
                                                                    if (pVal->exist.customData) {
                                                                    	ret = Telemetry_customData_IsConstraintValid((&(pVal->customData)), pErrCode);
                                                                    }
                                                                }   /*COVERAGE_IGNORE*/
                                                            }   /*COVERAGE_IGNORE*/
                                                        }   /*COVERAGE_IGNORE*/
                                                    }   /*COVERAGE_IGNORE*/
                                                }   /*COVERAGE_IGNORE*/
                                            }   /*COVERAGE_IGNORE*/
                                        }   /*COVERAGE_IGNORE*/
                                    }   /*COVERAGE_IGNORE*/
                                }   /*COVERAGE_IGNORE*/
                            }   /*COVERAGE_IGNORE*/
                        }   /*COVERAGE_IGNORE*/
                    }   /*COVERAGE_IGNORE*/
                }   /*COVERAGE_IGNORE*/
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void Telemetry_payloadCallsign_Initialize(Telemetry_payloadCallsign pVal)
{
	(void)pVal;


	memset(pVal, '-', 15);
	pVal[15] = 0;

}
void Telemetry_sequenceNumber_Initialize(Telemetry_sequenceNumber* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void Telemetry_timeOfDaySeconds_Initialize(Telemetry_timeOfDaySeconds* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void Telemetry_latitude_Initialize(Telemetry_latitude* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void Telemetry_longitude_Initialize(Telemetry_longitude* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void Telemetry_altitudeMeters_Initialize(Telemetry_altitudeMeters* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void Telemetry_velocityHorizontalKilometersPerHour_Initialize(Telemetry_velocityHorizontalKilometersPerHour* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void Telemetry_gnssSatellitesVisible_Initialize(Telemetry_gnssSatellitesVisible* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void Telemetry_ascentRateCentimetersPerSecond_Initialize(Telemetry_ascentRateCentimetersPerSecond* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void Telemetry_pressurehPa_x10_Initialize(Telemetry_pressurehPa_x10* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void Telemetry_humidityPercentage_Initialize(Telemetry_humidityPercentage* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void Telemetry_counts_Initialize(Telemetry_counts* pVal)
{
	(void)pVal;

    int i1;

	i1 = 0;
	while (i1< 8) {
	    pVal->arr[i1] = 0LL;
	    i1 = i1 + 1;
	}
	pVal->nCount = 1;
}
void Telemetry_customData_Initialize(Telemetry_customData* pVal)
{
	(void)pVal;


	memset(pVal->arr, 0x0, 255);
	pVal->nCount = 0;

}
void Telemetry_Initialize(Telemetry* pVal)
{
	(void)pVal;


	/*set extensionMarkerForASN1CC */
	pVal->exist.extensionMarkerForASN1CC = 1;
	pVal->extensionMarkerForASN1CC = FALSE;
	/*set payloadCallsign */
	Telemetry_payloadCallsign_Initialize(pVal->payloadCallsign);
	/*set sequenceNumber */
	Telemetry_sequenceNumber_Initialize((&(pVal->sequenceNumber)));
	/*set timeOfDaySeconds */
	Telemetry_timeOfDaySeconds_Initialize((&(pVal->timeOfDaySeconds)));
	/*set latitude */
	Telemetry_latitude_Initialize((&(pVal->latitude)));
	/*set longitude */
	Telemetry_longitude_Initialize((&(pVal->longitude)));
	/*set altitudeMeters */
	Telemetry_altitudeMeters_Initialize((&(pVal->altitudeMeters)));
	/*set extraSensors */
	pVal->exist.extraSensors = 1;
	AdditionalSensors_Initialize((&(pVal->extraSensors)));
	/*set velocityHorizontalKilometersPerHour */
	pVal->exist.velocityHorizontalKilometersPerHour = 1;
	Telemetry_velocityHorizontalKilometersPerHour_Initialize((&(pVal->velocityHorizontalKilometersPerHour)));
	/*set gnssSatellitesVisible */
	pVal->exist.gnssSatellitesVisible = 1;
	Telemetry_gnssSatellitesVisible_Initialize((&(pVal->gnssSatellitesVisible)));
	/*set ascentRateCentimetersPerSecond */
	pVal->exist.ascentRateCentimetersPerSecond = 1;
	Telemetry_ascentRateCentimetersPerSecond_Initialize((&(pVal->ascentRateCentimetersPerSecond)));
	/*set pressurehPa_x10 */
	pVal->exist.pressurehPa_x10 = 1;
	Telemetry_pressurehPa_x10_Initialize((&(pVal->pressurehPa_x10)));
	/*set temperatureCelsius_x10 */
	pVal->exist.temperatureCelsius_x10 = 1;
	TemperatureSensors_Initialize((&(pVal->temperatureCelsius_x10)));
	/*set humidityPercentage */
	pVal->exist.humidityPercentage = 1;
	Telemetry_humidityPercentage_Initialize((&(pVal->humidityPercentage)));
	/*set milliVolts */
	pVal->exist.milliVolts = 1;
	MilliVoltSensors_Initialize((&(pVal->milliVolts)));
	/*set counts */
	pVal->exist.counts = 1;
	Telemetry_counts_Initialize((&(pVal->counts)));
	/*set gnssPowerSaveState */
	pVal->exist.gnssPowerSaveState = 1;
	GnssPowerSaveState_Initialize((&(pVal->gnssPowerSaveState)));
	/*set customData */
	pVal->exist.customData = 1;
	Telemetry_customData_Initialize((&(pVal->customData)));
}

flag Telemetry_Encode(const Telemetry* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	int i1;
	asn1SccSint nStringLength;
	*pErrCode = 0;
	ret = bCheckConstraints ? Telemetry_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,pVal->exist.extensionMarkerForASN1CC);
	    if (ret) {
	        BitStream_AppendBit(pBitStrm,pVal->exist.extraSensors);
	        if (ret) {
	            BitStream_AppendBit(pBitStrm,pVal->exist.velocityHorizontalKilometersPerHour);
	            if (ret) {
	                BitStream_AppendBit(pBitStrm,pVal->exist.gnssSatellitesVisible);
	                if (ret) {
	                    BitStream_AppendBit(pBitStrm,pVal->exist.ascentRateCentimetersPerSecond);
	                    if (ret) {
	                        BitStream_AppendBit(pBitStrm,pVal->exist.pressurehPa_x10);
	                        if (ret) {
	                            BitStream_AppendBit(pBitStrm,pVal->exist.temperatureCelsius_x10);
	                            if (ret) {
	                                BitStream_AppendBit(pBitStrm,pVal->exist.humidityPercentage);
	                                if (ret) {
	                                    BitStream_AppendBit(pBitStrm,pVal->exist.milliVolts);
	                                    if (ret) {
	                                        BitStream_AppendBit(pBitStrm,pVal->exist.counts);
	                                        if (ret) {
	                                            BitStream_AppendBit(pBitStrm,pVal->exist.gnssPowerSaveState);
	                                            if (ret) {
	                                                BitStream_AppendBit(pBitStrm,pVal->exist.customData);
	                                                if (ret) {
	                                                    /*Encode extensionMarkerForASN1CC */
	                                                    if (pVal->exist.extensionMarkerForASN1CC) {
	                                                    	BitStream_AppendBit(pBitStrm,pVal->extensionMarkerForASN1CC);
	                                                    }
	                                                    if (ret) {
	                                                        /*Encode payloadCallsign */
	                                                        nStringLength = strlen(pVal->payloadCallsign);
	                                                        /*ret = nStringLength >= 1 && nStringLength <= 15;*/
	                                                        BitStream_EncodeConstraintWholeNumber(pBitStrm, nStringLength, 1, 15);
	                                                        for(i1=0; (i1 < (int)nStringLength) && ret; i1++)
	                                                        {
	                                                        	static byte allowedCharSet[] = {0x2D,0x2F,0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37,
	                                                        	                                0x38,0x39,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,
	                                                        	                                0x49,0x4A,0x4B,0x4C,0x4D,0x4E,0x4F,0x50,0x51,0x52,
	                                                        	                                0x53,0x54,0x55,0x56,0x57,0x58,0x59,0x5A,0x61,0x62,
	                                                        	                                0x63,0x64,0x65,0x66,0x67,0x68,0x69,0x6A,0x6B,0x6C,
	                                                        	                                0x6D,0x6E,0x6F,0x70,0x71,0x72,0x73,0x74,0x75,0x76,
	                                                        	                                0x77,0x78,0x79,0x7A};
	                                                        	int charIndex = GetCharIndex(pVal->payloadCallsign[i1], allowedCharSet, 64);
	                                                        	BitStream_EncodeConstraintWholeNumber(pBitStrm, charIndex, 0, 63);
	                                                        }

	                                                        if (ret) {
	                                                            /*Encode sequenceNumber */
	                                                            BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->sequenceNumber, 0, 65535);
	                                                            if (ret) {
	                                                                /*Encode timeOfDaySeconds */
	                                                                BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->timeOfDaySeconds, -1, 86400);
	                                                                if (ret) {
	                                                                    /*Encode latitude */
	                                                                    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->latitude, -9000000, 9000000);
	                                                                    if (ret) {
	                                                                        /*Encode longitude */
	                                                                        BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->longitude, -18000000, 18000000);
	                                                                        if (ret) {
	                                                                            /*Encode altitudeMeters */
	                                                                            BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->altitudeMeters, -1000, 50000);
	                                                                            if (ret) {
	                                                                                /*Encode extraSensors */
	                                                                                if (pVal->exist.extraSensors) {
	                                                                                	ret = AdditionalSensors_Encode((&(pVal->extraSensors)), pBitStrm, pErrCode, FALSE);
	                                                                                }
	                                                                                if (ret) {
	                                                                                    /*Encode velocityHorizontalKilometersPerHour */
	                                                                                    if (pVal->exist.velocityHorizontalKilometersPerHour) {
	                                                                                    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->velocityHorizontalKilometersPerHour, 0, 512);
	                                                                                    }
	                                                                                    if (ret) {
	                                                                                        /*Encode gnssSatellitesVisible */
	                                                                                        if (pVal->exist.gnssSatellitesVisible) {
	                                                                                        	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->gnssSatellitesVisible, 0, 31);
	                                                                                        }
	                                                                                        if (ret) {
	                                                                                            /*Encode ascentRateCentimetersPerSecond */
	                                                                                            if (pVal->exist.ascentRateCentimetersPerSecond) {
	                                                                                            	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->ascentRateCentimetersPerSecond, -32767, 32767);
	                                                                                            }
	                                                                                            if (ret) {
	                                                                                                /*Encode pressurehPa_x10 */
	                                                                                                if (pVal->exist.pressurehPa_x10) {
	                                                                                                	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->pressurehPa_x10, 0, 12000);
	                                                                                                }
	                                                                                                if (ret) {
	                                                                                                    /*Encode temperatureCelsius_x10 */
	                                                                                                    if (pVal->exist.temperatureCelsius_x10) {
	                                                                                                    	ret = TemperatureSensors_Encode((&(pVal->temperatureCelsius_x10)), pBitStrm, pErrCode, FALSE);
	                                                                                                    }
	                                                                                                    if (ret) {
	                                                                                                        /*Encode humidityPercentage */
	                                                                                                        if (pVal->exist.humidityPercentage) {
	                                                                                                        	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->humidityPercentage, 0, 100);
	                                                                                                        }
	                                                                                                        if (ret) {
	                                                                                                            /*Encode milliVolts */
	                                                                                                            if (pVal->exist.milliVolts) {
	                                                                                                            	ret = MilliVoltSensors_Encode((&(pVal->milliVolts)), pBitStrm, pErrCode, FALSE);
	                                                                                                            }
	                                                                                                            if (ret) {
	                                                                                                                /*Encode counts */
	                                                                                                                if (pVal->exist.counts) {
	                                                                                                                	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->counts.nCount, 1, 8);
	                                                                                                                	for(i1=0; (i1 < (int)pVal->counts.nCount) && ret; i1++)
	                                                                                                                	{
	                                                                                                                		BitStream_EncodeUnConstraintWholeNumber(pBitStrm, pVal->counts.arr[i1]);
	                                                                                                                	}
	                                                                                                                }
	                                                                                                                if (ret) {
	                                                                                                                    /*Encode gnssPowerSaveState */
	                                                                                                                    if (pVal->exist.gnssPowerSaveState) {
	                                                                                                                    	ret = GnssPowerSaveState_Encode((&(pVal->gnssPowerSaveState)), pBitStrm, pErrCode, FALSE);
	                                                                                                                    }
	                                                                                                                    if (ret) {
	                                                                                                                        /*Encode customData */
	                                                                                                                        if (pVal->exist.customData) {
	                                                                                                                        	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->customData.nCount, 0, 255);
	                                                                                                                        	ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->customData.arr, pVal->customData.nCount);
	                                                                                                                        }
	                                                                                                                    }   /*COVERAGE_IGNORE*/
	                                                                                                                }   /*COVERAGE_IGNORE*/
	                                                                                                            }   /*COVERAGE_IGNORE*/
	                                                                                                        }   /*COVERAGE_IGNORE*/
	                                                                                                    }   /*COVERAGE_IGNORE*/
	                                                                                                }   /*COVERAGE_IGNORE*/
	                                                                                            }   /*COVERAGE_IGNORE*/
	                                                                                        }   /*COVERAGE_IGNORE*/
	                                                                                    }   /*COVERAGE_IGNORE*/
	                                                                                }   /*COVERAGE_IGNORE*/
	                                                                            }   /*COVERAGE_IGNORE*/
	                                                                        }   /*COVERAGE_IGNORE*/
	                                                                    }   /*COVERAGE_IGNORE*/
	                                                                }   /*COVERAGE_IGNORE*/
	                                                            }   /*COVERAGE_IGNORE*/
	                                                        }   /*COVERAGE_IGNORE*/
	                                                    }   /*COVERAGE_IGNORE*/
	                                                }   /*COVERAGE_IGNORE*/
	                                            }   /*COVERAGE_IGNORE*/
	                                        }   /*COVERAGE_IGNORE*/
	                                    }   /*COVERAGE_IGNORE*/
	                                }   /*COVERAGE_IGNORE*/
	                            }   /*COVERAGE_IGNORE*/
	                        }   /*COVERAGE_IGNORE*/
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag Telemetry_Decode(Telemetry* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	flag presenceBit;
	int i1;
	asn1SccSint nStringLength;
	asn1SccSint nCount;

	ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	pVal->exist.extensionMarkerForASN1CC = presenceBit == 0 ? 0 : 1;
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	if (ret) {
	    ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	    pVal->exist.extraSensors = presenceBit == 0 ? 0 : 1;
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	    if (ret) {
	        ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	        pVal->exist.velocityHorizontalKilometersPerHour = presenceBit == 0 ? 0 : 1;
	        *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	        if (ret) {
	            ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	            pVal->exist.gnssSatellitesVisible = presenceBit == 0 ? 0 : 1;
	            *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	            if (ret) {
	                ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	                pVal->exist.ascentRateCentimetersPerSecond = presenceBit == 0 ? 0 : 1;
	                *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	                if (ret) {
	                    ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	                    pVal->exist.pressurehPa_x10 = presenceBit == 0 ? 0 : 1;
	                    *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	                    if (ret) {
	                        ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	                        pVal->exist.temperatureCelsius_x10 = presenceBit == 0 ? 0 : 1;
	                        *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	                        if (ret) {
	                            ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	                            pVal->exist.humidityPercentage = presenceBit == 0 ? 0 : 1;
	                            *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	                            if (ret) {
	                                ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	                                pVal->exist.milliVolts = presenceBit == 0 ? 0 : 1;
	                                *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	                                if (ret) {
	                                    ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	                                    pVal->exist.counts = presenceBit == 0 ? 0 : 1;
	                                    *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	                                    if (ret) {
	                                        ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	                                        pVal->exist.gnssPowerSaveState = presenceBit == 0 ? 0 : 1;
	                                        *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	                                        if (ret) {
	                                            ret = BitStream_ReadBit(pBitStrm, &presenceBit);
	                                            pVal->exist.customData = presenceBit == 0 ? 0 : 1;
	                                            *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY;
	                                            if (ret) {
	                                                /*Decode extensionMarkerForASN1CC */
	                                                if (pVal->exist.extensionMarkerForASN1CC) {
	                                                	ret = BitStream_ReadBit(pBitStrm, (&(pVal->extensionMarkerForASN1CC)));
	                                                	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_EXTENSIONMARKERFORASN1CC;
	                                                }
	                                                if (ret) {
	                                                    /*Decode payloadCallsign */
	                                                    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nStringLength, 1, 15);
	                                                    for(i1=0; (i1 < (int)nStringLength) && ret; i1++)
	                                                    {
	                                                    	static byte allowedCharSet[] = {0x2D,0x2F,0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37,
	                                                    	                                0x38,0x39,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,
	                                                    	                                0x49,0x4A,0x4B,0x4C,0x4D,0x4E,0x4F,0x50,0x51,0x52,
	                                                    	                                0x53,0x54,0x55,0x56,0x57,0x58,0x59,0x5A,0x61,0x62,
	                                                    	                                0x63,0x64,0x65,0x66,0x67,0x68,0x69,0x6A,0x6B,0x6C,
	                                                    	                                0x6D,0x6E,0x6F,0x70,0x71,0x72,0x73,0x74,0x75,0x76,
	                                                    	                                0x77,0x78,0x79,0x7A};
	                                                    	asn1SccSint charIndex = 0;
	                                                    	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &charIndex, 0, 63);
	                                                    	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_PAYLOADCALLSIGN;
	                                                    	if (ret && (charIndex < 0 || charIndex > 63)) { ret = FALSE; *pErrCode = ERR_UPER_DECODE_TELEMETRY_PAYLOADCALLSIGN; }
	                                                    	pVal->payloadCallsign[i1] = ret ? allowedCharSet[charIndex] : '\0' ;
	                                                    }
	                                                    pVal->payloadCallsign[nStringLength] = 0x0;
	                                                    if (ret) {
	                                                        /*Decode sequenceNumber */
	                                                        ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->sequenceNumber)), 0, 65535);
	                                                        *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_SEQUENCENUMBER;
	                                                        if (ret) {
	                                                            /*Decode timeOfDaySeconds */
	                                                            ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->timeOfDaySeconds)), -1, 86400);
	                                                            *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_TIMEOFDAYSECONDS;
	                                                            if (ret) {
	                                                                /*Decode latitude */
	                                                                ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->latitude)), -9000000, 9000000);
	                                                                *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_LATITUDE;
	                                                                if (ret) {
	                                                                    /*Decode longitude */
	                                                                    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->longitude)), -18000000, 18000000);
	                                                                    *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_LONGITUDE;
	                                                                    if (ret) {
	                                                                        /*Decode altitudeMeters */
	                                                                        ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->altitudeMeters)), -1000, 50000);
	                                                                        *pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_ALTITUDEMETERS;
	                                                                        if (ret) {
	                                                                            /*Decode extraSensors */
	                                                                            if (pVal->exist.extraSensors) {
	                                                                            	ret = AdditionalSensors_Decode((&(pVal->extraSensors)), pBitStrm, pErrCode);
	                                                                            }
	                                                                            if (ret) {
	                                                                                /*Decode velocityHorizontalKilometersPerHour */
	                                                                                if (pVal->exist.velocityHorizontalKilometersPerHour) {
	                                                                                	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->velocityHorizontalKilometersPerHour)), 0, 512);
	                                                                                	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_VELOCITYHORIZONTALKILOMETERSPERHOUR;
	                                                                                }
	                                                                                if (ret) {
	                                                                                    /*Decode gnssSatellitesVisible */
	                                                                                    if (pVal->exist.gnssSatellitesVisible) {
	                                                                                    	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->gnssSatellitesVisible)), 0, 31);
	                                                                                    	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_GNSSSATELLITESVISIBLE;
	                                                                                    }
	                                                                                    if (ret) {
	                                                                                        /*Decode ascentRateCentimetersPerSecond */
	                                                                                        if (pVal->exist.ascentRateCentimetersPerSecond) {
	                                                                                        	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->ascentRateCentimetersPerSecond)), -32767, 32767);
	                                                                                        	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_ASCENTRATECENTIMETERSPERSECOND;
	                                                                                        }
	                                                                                        if (ret) {
	                                                                                            /*Decode pressurehPa_x10 */
	                                                                                            if (pVal->exist.pressurehPa_x10) {
	                                                                                            	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->pressurehPa_x10)), 0, 12000);
	                                                                                            	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_PRESSUREHPA_X10;
	                                                                                            }
	                                                                                            if (ret) {
	                                                                                                /*Decode temperatureCelsius_x10 */
	                                                                                                if (pVal->exist.temperatureCelsius_x10) {
	                                                                                                	ret = TemperatureSensors_Decode((&(pVal->temperatureCelsius_x10)), pBitStrm, pErrCode);
	                                                                                                }
	                                                                                                if (ret) {
	                                                                                                    /*Decode humidityPercentage */
	                                                                                                    if (pVal->exist.humidityPercentage) {
	                                                                                                    	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->humidityPercentage)), 0, 100);
	                                                                                                    	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_HUMIDITYPERCENTAGE;
	                                                                                                    }
	                                                                                                    if (ret) {
	                                                                                                        /*Decode milliVolts */
	                                                                                                        if (pVal->exist.milliVolts) {
	                                                                                                        	ret = MilliVoltSensors_Decode((&(pVal->milliVolts)), pBitStrm, pErrCode);
	                                                                                                        }
	                                                                                                        if (ret) {
	                                                                                                            /*Decode counts */
	                                                                                                            if (pVal->exist.counts) {
	                                                                                                            	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 8);
	                                                                                                            	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_COUNTS;
	                                                                                                            	pVal->counts.nCount = (long)nCount;
	                                                                                                            	for(i1=0; (i1 < (int)pVal->counts.nCount) && ret; i1++)
	                                                                                                            	{
	                                                                                                            		ret = BitStream_DecodeUnConstraintWholeNumber(pBitStrm, (&(pVal->counts.arr[i1])));   
	                                                                                                            		*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_COUNTS_ELM;                               
	                                                                                                            	}
	                                                                                                            }
	                                                                                                            if (ret) {
	                                                                                                                /*Decode gnssPowerSaveState */
	                                                                                                                if (pVal->exist.gnssPowerSaveState) {
	                                                                                                                	ret = GnssPowerSaveState_Decode((&(pVal->gnssPowerSaveState)), pBitStrm, pErrCode);
	                                                                                                                }
	                                                                                                                if (ret) {
	                                                                                                                    /*Decode customData */
	                                                                                                                    if (pVal->exist.customData) {
	                                                                                                                    	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 255);
	                                                                                                                    	*pErrCode = ret ? 0 : ERR_UPER_DECODE_TELEMETRY_CUSTOMDATA;
	                                                                                                                    	pVal->customData.nCount = (long)nCount;
	                                                                                                                    	ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->customData.arr, pVal->customData.nCount);
	                                                                                                                    }
	                                                                                                                }   /*COVERAGE_IGNORE*/
	                                                                                                            }   /*COVERAGE_IGNORE*/
	                                                                                                        }   /*COVERAGE_IGNORE*/
	                                                                                                    }   /*COVERAGE_IGNORE*/
	                                                                                                }   /*COVERAGE_IGNORE*/
	                                                                                            }   /*COVERAGE_IGNORE*/
	                                                                                        }   /*COVERAGE_IGNORE*/
	                                                                                    }   /*COVERAGE_IGNORE*/
	                                                                                }   /*COVERAGE_IGNORE*/
	                                                                            }   /*COVERAGE_IGNORE*/
	                                                                        }   /*COVERAGE_IGNORE*/
	                                                                    }   /*COVERAGE_IGNORE*/
	                                                                }   /*COVERAGE_IGNORE*/
	                                                            }   /*COVERAGE_IGNORE*/
	                                                        }   /*COVERAGE_IGNORE*/
	                                                    }   /*COVERAGE_IGNORE*/
	                                                }   /*COVERAGE_IGNORE*/
	                                            }   /*COVERAGE_IGNORE*/
	                                        }   /*COVERAGE_IGNORE*/
	                                    }   /*COVERAGE_IGNORE*/
	                                }   /*COVERAGE_IGNORE*/
	                            }   /*COVERAGE_IGNORE*/
	                        }   /*COVERAGE_IGNORE*/
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && Telemetry_IsConstraintValid(pVal, pErrCode);
}


